analyzer:
  errors:
    deprecated_member_use: ignore
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "lib/generated_plugin_registrant.cc"

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - always_declare_return_types
    - camel_case_types
